# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install bash and curl
RUN apk add --no-cache bash curl

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash

# Set Bun environment variables
ENV BUN_INSTALL=/root/.bun
ENV PATH=$BUN_INSTALL/bin:$PATH

# Create app directory and copy source files
WORKDIR /app
COPY . .

# Install dependencies using Bun
RUN bun install

# Build the project using Bun
RUN bun run build

# Expose any necessary ports (if applicable) and set the entrypoint
CMD ["node", "build/index.js"]
